### ISSUE TITLE
Can't reproduce manuscript results of Jackstraw PCA 

### ISSUE THREAD

**Issue by cristianregep** [klarman-cell-observatory/Perturb-CITE-seq#1] opened 2021-04-03 10:18 UTC
Firstly i want to say congrats on a great paper on perturb-seq. i've really enjoyed the analysis and working with the data. I did run into some trouble, described below. 

I've tried using the functions https://github.com/klarman-cell-observatory/Perturb-CITE-seq/blob/main/jackstraw_PCA.py, but I can't reproduce the results in the manuscript, i.e. i get 13000 genes significant for first program in Co-culture MOI=1 (as opposed to around 700 in Extended Data Fig. 5f)

The implementation also seems to be different. The Jackstraw PCA algorithm in Chung and Storey permutes s rows, the one in https://github.com/klarman-cell-observatory/Perturb-CITE-seq/blob/main/jackstraw_PCA.py subsamples (see attached)
<img width="661" alt="Screenshot 2021-04-03 at 11 09 52" src="https://user-images.githubusercontent.com/240387/113475435-9eb5e900-946d-11eb-93e8-a0a5d1ed7862.png">
. The one in Chung and Storey also calculates an F-statistic and uses that to establish significance. 

I might be missing something, so could you please upload in the entire script that takes the expression matrix and outputs the significant genes?

**Comment by CFrangieh** [comment] 2021-04-27 12:40
Hi Cristian

Thank you for reaching out. You should be able to reproduce the Jackstraw programs by running these lines:

```
from sklearn.decomposition import PCA

PCA_null_distribs = calc_PCA_null(expr_mat, n_cells=expr_mat.shape[0], n_reps=150000, n_comps=50)
pca = PCA(n_components=50)
X_pca = pca.fit_transform(expr_mat.T)
gene_pvals = calc_gene_pvals(X_pca.T, PCA_null_distribs)
genes_per_mod = np.array([np.where(gene_pvals[mod_i, :] < 0.03)[0].size for mod_i in range(50)])
gene_inds_per_mod = np.array([np.where(gene_pvals[mod_i, :] < 0.03)[0] for mod_i in range(50)])
```

The array "genes_per_mod" will allow you to reproduce Extended Data Figures 5a-5c, and the feature indices themselves will be in "gene_inds_per_mod." 

Also make sure you are using the log TPM expression matrix from whichever condition you are using. I would also recommend setting "n_cells" equal to the number of cells in the condition if that is feasible on your system. Because it is an empirical test, there may be slight variations in your results but they should generally agree.

You are right that we subsample rather than permute for speed. Here is a description of our procedure: Expression matrices from each condition were processed separately using MOI = 1 cells only. A subset of 150 features (out of all genes passing QC and all 20 CITE proteins) was randomly sampled, followed by PCA, for 150,000 iterations. This allowed a PC-wise calculation of the synthetic null distribution of PC loadings. PCA was then run on the full expression matrix, to calculate an empirical p value for each feature. A threshold (p < 0.03) was used to assign specific features to each program (PC) to obtain programs of reasonable biological size. 

Thank you
Chris

**Closed as completed** 2022-05-24 02:27 UTC
